blank_issues_enabled: true
contact_links:
  - name: "Cộng đồng Embedded Linux / Community"
    url: "https://www.facebook.com/groups/1291288389349930/"
    about: "Hỏi đáp, trao đổi nhanh về bài viết và board."
